In [2]:
import torch
import numpy as np
from pathlib import Path
import xarray as xr

msl_dir = Path("/data/jiyilun/typhoon/download/era5")
corrupt_files = []
for era5_file in sorted(msl_dir.glob("*.nc")):
    right = True
    era5_hour = xr.open_dataset(era5_file)
    for var in era5_hour.data_vars:
        if np.isnan(era5_hour[var].values).any():
            print(f"NaN found in {era5_file.stem}.{var}")
            print(f"NaN proportion: {np.isnan(era5_hour[var].values).mean()}")
            right = False
    if right:
        print(f"File {era5_file.stem} is OK.")
    else:
        print(f"File {era5_file.stem} is corrupt.")
        corrupt_files.append(era5_file)
print(corrupt_files)


File 2011050706 is OK.
File 2011050712 is OK.
File 2011050718 is OK.
File 2011050800 is OK.
File 2011050806 is OK.
File 2011050812 is OK.
File 2011050818 is OK.
File 2011050900 is OK.
File 2011050906 is OK.
File 2011052112 is OK.
File 2011052118 is OK.
File 2011052200 is OK.
File 2011052206 is OK.
File 2011052212 is OK.
File 2011052218 is OK.
File 2011052300 is OK.
File 2011052306 is OK.
File 2011052312 is OK.
File 2011052318 is OK.
File 2011052400 is OK.
File 2011052406 is OK.
File 2011052412 is OK.
File 2011052418 is OK.
File 2011052500 is OK.
File 2011052506 is OK.
File 2011052512 is OK.
File 2011052518 is OK.
File 2011052600 is OK.
File 2011052606 is OK.
File 2011052612 is OK.
File 2011061718 is OK.
File 2011061800 is OK.
File 2011061806 is OK.
File 2011061812 is OK.
File 2011061818 is OK.
File 2011061900 is OK.
File 2011061906 is OK.
File 2011061912 is OK.
File 2011061918 is OK.
File 2011062000 is OK.
File 2011062006 is OK.
File 2011062012 is OK.
File 2011062018 is OK.
File 201106

KeyboardInterrupt: 

In [ ]:
import xarray as xr
import pandas as pd
from datetime import datetime
era5_dir = Path("/data/jiyilun/typhoon/download/era5")
url = "gs://weatherbench2/datasets/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr"
era5_ds = xr.open_zarr(url)

In [66]:
time_str = "2018080500"


era5_ds["mean_sea_level_pressure"].sel(
    time=pd.to_datetime(time_str, format="%Y%m%d%H")
).isel(
    longitude=slice(400, 720),
    latitude=slice(121, 361)
).compute()

<xarray.DataArray 'mean_sea_level_pressure' (latitude: 240, longitude: 320)>
array([[100844.15 , 100863.42 , 100886.37 , ..., 100228.164, 100235.2  ,
        100242.234],
       [100833.75 , 100855.47 , 100885.75 , ..., 100262.43 , 100270.69 ,
        100278.49 ],
       [100824.11 , 100854.24 , 100887.74 , ..., 100298.375, 100307.7  ,
        100316.88 ],
       ...,
       [101453.4  , 101351.984, 101287.125, ..., 100890.65 , 100890.95 ,
        100891.26 ],
       [101484.15 , 101399.25 , 101341.125, ..., 100894.47 , 100894.625,
        100894.47 ],
       [101374.93 , 101479.25 , 101429.99 , ..., 100897.375, 100897.375,
        100897.23 ]], dtype=float32)
Coordinates:
  * latitude   (latitude) float32 59.75 59.5 59.25 59.0 ... 0.75 0.5 0.25 0.0
  * longitude  (longitude) float32 100.0 100.2 100.5 100.8 ... 179.2 179.5 179.8
    time       datetime64[ns] 2018-08-05
Attributes:
    long_name:      Mean sea level pressure
    short_name:     msl
    standard_name:  air_pressure_at_mean_sea_level
    units:          Pa

In [43]:
era5_ds_hour = xr.open_dataset(era5_dir / "2018080500.nc")

In [53]:
var_names = [
    "10m_u_component_of_wind",
    "10m_v_component_of_wind",
    "2m_temperature",
    "mean_sea_level_pressure",
    "temperature",
    "u_component_of_wind",
    "v_component_of_wind",
    "specific_humidity",
    "geopotential",
]
print(era5_ds["geopotential"].sel(
        time=datetime(2018, 8, 5, 0)
    ).isel(
        longitude=slice(400, 720),
        latitude=slice(121, 361)
    ).values - era5_ds_hour["geopotential"].values)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
